# Generated by Django 4.1.3 on 2022-11-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placemodel',
            name='capacity',
            field=models.SmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='placemodel',
            name='img',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placemodel',
            name='locality',
            field=models.CharField(default='Margao', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placeimagesmodel',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
