# Generated by Django 4.1.3 on 2022-11-03 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_placemodel_capacity_placemodel_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslotmodel',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_time_slots', to='app.placemodel'),
        ),
    ]
