# Generated by Django 4.1.3 on 2022-11-03 15:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitemsmodel',
            old_name='appoitment',
            new_name='date',
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('has_attended', models.BooleanField(default=False)),
                ('img', models.ImageField(upload_to='tickets')),
                ('valid_till', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_ticket', to='cart.ordermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
