# Generated by Django 4.1.3 on 2022-11-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_appoitment_orderitemsmodel_date_ticketmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='qr_img',
            field=models.ImageField(blank=True, null=True, upload_to='QR'),
        ),
    ]
