# Generated by Django 4.1.3 on 2022-11-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_orderitemsmodel_has_attended_orderitemsmodel_ticket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='qr_img',
        ),
        migrations.AddField(
            model_name='orderitemsmodel',
            name='qr_img',
            field=models.ImageField(blank=True, null=True, upload_to='QR'),
        ),
    ]
